train_params:
    epoch: 100
    batch_size: 4

data_params:
    style: "CSQ"
    vocab_size: 270
    seq_len: 2048
    # 


VAE:
  epoch: 100
  warmup_epoch: 20
  warmup_rate: 0.1
  batch_size: 4
  d_model: 2048
  input_size: 512
  hidden_size: 1024
  encoder_num_layers: 2
  conductor_num_layers: 2
  decoder_num_layers: 2
  dropout: 0.1
  CSQ:
    vocab_size: 270
    seq_len: 2048
    num_tracks: 4
  CPI:
    vocab_size: 389
    seq_len: 2048
    num_tracks: 4

Transformer:
  epoch: 100
  batch_size: 2
  n_layer: 6
  n_head: 8
  d_model: 512
  d_head: 64
  d_inner: 2048
  dropout: 0.1
  CSQ:
    vocab_size: 270
    seq_len: 2048
  CPI:
    vocab_size: 389
    seq_len: 2048